production:
  address: "smtp.mailgun.org"
  port: 587"
  domain: "mg.air-fitsense.com"
  authentication: "plain"
  user_name: "postmaster@mg.air.air-fitsense.com"
  password: "h23436358"
  enable_starttls_auto: true
